var app = angular.module('main', ['ngTable']).
    controller('DemoCtrl', function($scope, ngTableParams) {
        var data = [
            {
                "_id": "545163fdecf44af8e066f465",
                "id": 115,
                "flt_date": "2012-01-01 00:00:00",
                "hobbs_out": 705.7,
                "hobbs_in": 708.7,
                "fuel_out": 114,
                "fuel_in": 64,
                "fuel_purch": 39.7,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f466",
                "id": 116,
                "flt_date": "2012-01-06 00:00:00",
                "hobbs_out": 708.7,
                "hobbs_in": 709.3,
                "fuel_out": 64,
                "fuel_in": 51,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f467",
                "id": 117,
                "flt_date": "2012-01-14 00:00:00",
                "hobbs_out": 709.3,
                "hobbs_in": 711,
                "fuel_out": 51,
                "fuel_in": 92,
                "fuel_purch": 66.2,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f468",
                "id": 118,
                "flt_date": "2012-01-28 00:00:00",
                "hobbs_out": 711,
                "hobbs_in": 712.5,
                "fuel_out": 92,
                "fuel_in": 65,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f469",
                "id": 119,
                "flt_date": "2012-01-29 00:00:00",
                "hobbs_out": 712.5,
                "hobbs_in": 713.6,
                "fuel_out": 65,
                "fuel_in": 45,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 9.1,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f46a",
                "id": 120,
                "flt_date": "2012-03-15 00:00:00",
                "hobbs_out": 713.6,
                "hobbs_in": 713.8,
                "fuel_out": 45,
                "fuel_in": 40,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f46b",
                "id": 121,
                "flt_date": "2012-03-16 00:00:00",
                "hobbs_out": 713.8,
                "hobbs_in": 714.7,
                "fuel_out": 40,
                "fuel_in": 108,
                "fuel_purch": 85.1,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f46c",
                "id": 122,
                "flt_date": "2012-03-17 00:00:00",
                "hobbs_out": 714.7,
                "hobbs_in": 717.3,
                "fuel_out": 108,
                "fuel_in": 62,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f46d",
                "id": 123,
                "flt_date": "2012-03-23 00:00:00",
                "hobbs_out": 717.3,
                "hobbs_in": 718,
                "fuel_out": 62,
                "fuel_in": 108,
                "fuel_purch": 56.9,
                "fuel_cost": 5.25,
                "oil_added": 1,
                "oil_dipstick": 4.8,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f46e",
                "id": 124,
                "flt_date": "2012-03-25 00:00:00",
                "hobbs_out": 718,
                "hobbs_in": 719.2,
                "fuel_out": 106,
                "fuel_in": 85,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f46f",
                "id": 125,
                "flt_date": "2012-04-06 00:00:00",
                "hobbs_out": 719.2,
                "hobbs_in": 720.3,
                "fuel_out": 85,
                "fuel_in": 65,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f470",
                "id": 126,
                "flt_date": "2012-04-06 00:00:00",
                "hobbs_out": 720.3,
                "hobbs_in": 721.1,
                "fuel_out": 65,
                "fuel_in": 74,
                "fuel_purch": 22.4,
                "fuel_cost": 6.2,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f471",
                "id": 127,
                "flt_date": "2012-04-08 00:00:00",
                "hobbs_out": 721.1,
                "hobbs_in": 721.5,
                "fuel_out": 74,
                "fuel_in": 66,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f472",
                "id": 128,
                "flt_date": "2012-04-09 00:00:00",
                "hobbs_out": 721.5,
                "hobbs_in": 722.3,
                "fuel_out": 66,
                "fuel_in": 51,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f473",
                "id": 129,
                "flt_date": "2012-04-12 00:00:00",
                "hobbs_out": 722.3,
                "hobbs_in": 723,
                "fuel_out": 51,
                "fuel_in": 109,
                "fuel_purch": 71.8,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f474",
                "id": 130,
                "flt_date": "2012-04-14 00:00:00",
                "hobbs_out": 723,
                "hobbs_in": 724.6,
                "fuel_out": 109,
                "fuel_in": 81,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f475",
                "id": 131,
                "flt_date": "2012-04-14 00:00:00",
                "hobbs_out": 724.6,
                "hobbs_in": 725.9,
                "fuel_out": 81,
                "fuel_in": 56,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f476",
                "id": 132,
                "flt_date": "2012-04-18 00:00:00",
                "hobbs_out": 725.9,
                "hobbs_in": 727.4,
                "fuel_out": 56,
                "fuel_in": 87,
                "fuel_purch": 56.2,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 8.6,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f477",
                "id": 133,
                "flt_date": "2012-04-22 00:00:00",
                "hobbs_out": 727.4,
                "hobbs_in": 729,
                "fuel_out": 87,
                "fuel_in": 85,
                "fuel_purch": 26.6,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f478",
                "id": 134,
                "flt_date": "2012-04-29 00:00:00",
                "hobbs_out": 729,
                "hobbs_in": 730.3,
                "fuel_out": 85,
                "fuel_in": 62,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f479",
                "id": 135,
                "flt_date": "2012-05-02 00:00:00",
                "hobbs_out": 730.3,
                "hobbs_in": 731.8,
                "fuel_out": 62,
                "fuel_in": 69,
                "fuel_purch": 30.3,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f47a",
                "id": 136,
                "flt_date": "2012-05-05 00:00:00",
                "hobbs_out": 731.8,
                "hobbs_in": 732.7,
                "fuel_out": 69,
                "fuel_in": 53,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f47b",
                "id": 137,
                "flt_date": "2012-05-13 00:00:00",
                "hobbs_out": 732.7,
                "hobbs_in": 734.9,
                "fuel_out": 53,
                "fuel_in": 35,
                "fuel_purch": 20.6,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f47c",
                "id": 138,
                "flt_date": "2012-05-25 00:00:00",
                "hobbs_out": 734.9,
                "hobbs_in": 736.4,
                "fuel_out": 35,
                "fuel_in": 94,
                "fuel_purch": 83,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f47d",
                "id": 139,
                "flt_date": "2012-05-26 00:00:00",
                "hobbs_out": 736.4,
                "hobbs_in": 737.6,
                "fuel_out": 94,
                "fuel_in": 75,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f47e",
                "id": 140,
                "flt_date": "2012-05-27 00:00:00",
                "hobbs_out": 737.6,
                "hobbs_in": 739,
                "fuel_out": 75,
                "fuel_in": 54,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f47f",
                "id": 141,
                "flt_date": "2012-06-01 00:00:00",
                "hobbs_out": 739,
                "hobbs_in": 740,
                "fuel_out": 54,
                "fuel_in": 38,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f480",
                "id": 142,
                "flt_date": "2012-06-02 00:00:00",
                "hobbs_out": 740,
                "hobbs_in": 743.7,
                "fuel_out": 38,
                "fuel_in": 47,
                "fuel_purch": 74,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 9.7,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f481",
                "id": 143,
                "flt_date": "2012-06-03 00:00:00",
                "hobbs_out": 743.7,
                "hobbs_in": 744.5,
                "fuel_out": 47,
                "fuel_in": 109,
                "fuel_purch": 75,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f482",
                "id": 144,
                "flt_date": "2012-06-15 00:00:00",
                "hobbs_out": 744.5,
                "hobbs_in": 745.4,
                "fuel_out": 109,
                "fuel_in": 93,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f483",
                "id": 145,
                "flt_date": "2012-06-19 00:00:00",
                "hobbs_out": 745.4,
                "hobbs_in": 746.4,
                "fuel_out": 93,
                "fuel_in": 76,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f484",
                "id": 146,
                "flt_date": "2012-06-30 00:00:00",
                "hobbs_out": 746.4,
                "hobbs_in": 747.5,
                "fuel_out": 76,
                "fuel_in": 56,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f485",
                "id": 147,
                "flt_date": "2012-07-01 00:00:00",
                "hobbs_out": 747.5,
                "hobbs_in": 749.2,
                "fuel_out": 56,
                "fuel_in": 111,
                "fuel_purch": 83.1,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f486",
                "id": 148,
                "flt_date": "2012-07-21 00:00:00",
                "hobbs_out": 749.2,
                "hobbs_in": 749.9,
                "fuel_out": 111,
                "fuel_in": 97,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f487",
                "id": 149,
                "flt_date": "2012-07-28 00:00:00",
                "hobbs_out": 749.9,
                "hobbs_in": 753.2,
                "fuel_out": 97,
                "fuel_in": 41,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f488",
                "id": 150,
                "flt_date": "2012-08-01 00:00:00",
                "hobbs_out": 753.2,
                "hobbs_in": 756.5,
                "fuel_out": 41,
                "fuel_in": 61,
                "fuel_purch": 71,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 13.2,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f489",
                "id": 151,
                "flt_date": "2012-08-11 00:00:00",
                "hobbs_out": 756.5,
                "hobbs_in": 757.1,
                "fuel_out": 61,
                "fuel_in": 51,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f48a",
                "id": 152,
                "flt_date": "2012-08-11 00:00:00",
                "hobbs_out": 757.1,
                "hobbs_in": 757.5,
                "fuel_out": 51,
                "fuel_in": 84,
                "fuel_purch": 46.3,
                "fuel_cost": 5.2,
                "oil_added": 1,
                "oil_dipstick": 3.9,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f48b",
                "id": 153,
                "flt_date": "2012-08-12 00:00:00",
                "hobbs_out": 757.5,
                "hobbs_in": 758.4,
                "fuel_out": 84,
                "fuel_in": 68,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f48c",
                "id": 154,
                "flt_date": "2012-08-12 00:00:00",
                "hobbs_out": 758.4,
                "hobbs_in": 759.3,
                "fuel_out": 68,
                "fuel_in": 97,
                "fuel_purch": 44,
                "fuel_cost": 5.99,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f48d",
                "id": 155,
                "flt_date": "2012-08-25 00:00:00",
                "hobbs_out": 759.3,
                "hobbs_in": 760.2,
                "fuel_out": 97,
                "fuel_in": 79,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f48e",
                "id": 156,
                "flt_date": "2012-08-25 00:00:00",
                "hobbs_out": 760.2,
                "hobbs_in": 760.9,
                "fuel_out": 79,
                "fuel_in": 64,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f48f",
                "id": 157,
                "flt_date": "2012-08-26 00:00:00",
                "hobbs_out": 760.9,
                "hobbs_in": 761.3,
                "fuel_out": 64,
                "fuel_in": 109,
                "fuel_purch": 48.5,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f490",
                "id": 158,
                "flt_date": "2012-08-27 00:00:00",
                "hobbs_out": 761.3,
                "hobbs_in": 763.2,
                "fuel_out": 109,
                "fuel_in": 74,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f491",
                "id": 159,
                "flt_date": "2012-09-04 00:00:00",
                "hobbs_out": 763.2,
                "hobbs_in": 765.2,
                "fuel_out": 74,
                "fuel_in": 81,
                "fuel_purch": 39.5,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f492",
                "id": 160,
                "flt_date": "2012-11-21 00:00:00",
                "hobbs_out": 765.4,
                "hobbs_in": 766.6,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f493",
                "id": 161,
                "flt_date": "2012-11-22 00:00:00",
                "hobbs_out": 766.6,
                "hobbs_in": 767.7,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 20.1,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f494",
                "id": 162,
                "flt_date": "2012-11-23 00:00:00",
                "hobbs_out": 767.7,
                "hobbs_in": 768.7,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f495",
                "id": 163,
                "flt_date": "2012-11-23 00:00:00",
                "hobbs_out": 768.7,
                "hobbs_in": 769.2,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f496",
                "id": 164,
                "flt_date": "2012-11-24 00:00:00",
                "hobbs_out": 769.2,
                "hobbs_in": 770.6,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f497",
                "id": 165,
                "flt_date": "2012-11-25 00:00:00",
                "hobbs_out": 770.6,
                "hobbs_in": 771.8,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 35.3,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f498",
                "id": 166,
                "flt_date": "2012-11-28 00:00:00",
                "hobbs_out": 771.8,
                "hobbs_in": 773,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f499",
                "id": 167,
                "flt_date": "2012-11-30 00:00:00",
                "hobbs_out": 773,
                "hobbs_in": 774.1,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f49a",
                "id": 168,
                "flt_date": "2012-12-01 00:00:00",
                "hobbs_out": 774.1,
                "hobbs_in": 774.7,
                "fuel_out": 0,
                "fuel_in": 0,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f49b",
                "id": 169,
                "flt_date": "2012-12-02 00:00:00",
                "hobbs_out": 774.7,
                "hobbs_in": 777.1,
                "fuel_out": 81,
                "fuel_in": 33,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f49c",
                "id": 170,
                "flt_date": "2012-12-03 00:00:00",
                "hobbs_out": 777.1,
                "hobbs_in": 777.5,
                "fuel_out": 33,
                "fuel_in": 70.1,
                "fuel_purch": 40.6,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f49d",
                "id": 171,
                "flt_date": "2012-12-07 00:00:00",
                "hobbs_out": 777.5,
                "hobbs_in": 779.8,
                "fuel_out": 70.1,
                "fuel_in": 28,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 14.4,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f49e",
                "id": 172,
                "flt_date": "2012-12-08 00:00:00",
                "hobbs_out": 779.8,
                "hobbs_in": 780.7,
                "fuel_out": 29.7,
                "fuel_in": 63.4,
                "fuel_purch": 49.3,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f49f",
                "id": 173,
                "flt_date": "2012-12-09 00:00:00",
                "hobbs_out": 780.7,
                "hobbs_in": 781.3,
                "fuel_out": 63.2,
                "fuel_in": 52.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a0",
                "id": 174,
                "flt_date": "2012-12-15 00:00:00",
                "hobbs_out": 781.3,
                "hobbs_in": 783.2,
                "fuel_out": 52.1,
                "fuel_in": 107.7,
                "fuel_purch": 89.9,
                "fuel_cost": 5.2,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a1",
                "id": 175,
                "flt_date": "2012-12-18 00:00:00",
                "hobbs_out": 783.2,
                "hobbs_in": 784.4,
                "fuel_out": 107.7,
                "fuel_in": 86.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a2",
                "id": 176,
                "flt_date": "2012-12-23 00:00:00",
                "hobbs_out": 784.4,
                "hobbs_in": 785.6,
                "fuel_out": 86.1,
                "fuel_in": 63.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a3",
                "id": 177,
                "flt_date": "2012-12-31 00:00:00",
                "hobbs_out": 785.6,
                "hobbs_in": 786.5,
                "fuel_out": 63.4,
                "fuel_in": 49.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a4",
                "id": 178,
                "flt_date": "2013-01-07 00:00:00",
                "hobbs_out": 786.5,
                "hobbs_in": 787.5,
                "fuel_out": 49.4,
                "fuel_in": 29.7,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a5",
                "id": 179,
                "flt_date": "2013-01-13 00:00:00",
                "hobbs_out": 787.5,
                "hobbs_in": 788,
                "fuel_out": 29.7,
                "fuel_in": 114,
                "fuel_purch": 91.5,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 10.9,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a6",
                "id": 180,
                "flt_date": "2013-01-17 00:00:00",
                "hobbs_out": 788,
                "hobbs_in": 788.8,
                "fuel_out": 114,
                "fuel_in": 97.3,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a7",
                "id": 181,
                "flt_date": "2013-01-18 00:00:00",
                "hobbs_out": 788.8,
                "hobbs_in": 789.6,
                "fuel_out": 97.3,
                "fuel_in": 80.7,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a8",
                "id": 182,
                "flt_date": "2013-01-18 00:00:00",
                "hobbs_out": 789.6,
                "hobbs_in": 791.2,
                "fuel_out": 80.7,
                "fuel_in": 74,
                "fuel_purch": 25.5,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4a9",
                "id": 183,
                "flt_date": "2013-01-20 00:00:00",
                "hobbs_out": 791.2,
                "hobbs_in": 792.6,
                "fuel_out": 74,
                "fuel_in": 44.2,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4aa",
                "id": 184,
                "flt_date": "2013-01-26 00:00:00",
                "hobbs_out": 792.6,
                "hobbs_in": 793.2,
                "fuel_out": 44.2,
                "fuel_in": 68.4,
                "fuel_purch": 33.3,
                "fuel_cost": 5.2,
                "oil_added": 1,
                "oil_dipstick": 10,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4ab",
                "id": 185,
                "flt_date": "2013-01-27 00:00:00",
                "hobbs_out": 793.2,
                "hobbs_in": 795,
                "fuel_out": 68.3,
                "fuel_in": 68,
                "fuel_purch": 30.4,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4ac",
                "id": 186,
                "flt_date": "2013-02-14 00:00:00",
                "hobbs_out": 795,
                "hobbs_in": 796.4,
                "fuel_out": 68.3,
                "fuel_in": 74,
                "fuel_purch": 33.4,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4ad",
                "id": 187,
                "flt_date": "2013-02-17 00:00:00",
                "hobbs_out": 796.4,
                "hobbs_in": 797.8,
                "fuel_out": 74,
                "fuel_in": 43.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4ae",
                "id": 188,
                "flt_date": "2013-03-01 00:00:00",
                "hobbs_out": 797.8,
                "hobbs_in": 800.4,
                "fuel_out": 114,
                "fuel_in": 114,
                "fuel_purch": 48.8,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4af",
                "id": 189,
                "flt_date": "2013-03-03 00:00:00",
                "hobbs_out": 800.4,
                "hobbs_in": 803.2,
                "fuel_out": 114,
                "fuel_in": 57.4,
                "fuel_purch": 0,
                "fuel_cost": 6.22,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b0",
                "id": 190,
                "flt_date": "2013-03-08 00:00:00",
                "hobbs_out": 803.2,
                "hobbs_in": 804.6,
                "fuel_out": 57.4,
                "fuel_in": 62.8,
                "fuel_purch": 34.5,
                "fuel_cost": 6.72,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b1",
                "id": 191,
                "flt_date": "2013-03-10 00:00:00",
                "hobbs_out": 804.6,
                "hobbs_in": 806.2,
                "fuel_out": 74,
                "fuel_in": 62,
                "fuel_purch": 27,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b2",
                "id": 192,
                "flt_date": "2013-03-15 00:00:00",
                "hobbs_out": 806.2,
                "hobbs_in": 806.9,
                "fuel_out": 61.9,
                "fuel_in": 90.7,
                "fuel_purch": 37.3,
                "fuel_cost": 5.2,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b3",
                "id": 193,
                "flt_date": "2013-03-17 00:00:00",
                "hobbs_out": 806.9,
                "hobbs_in": 808.1,
                "fuel_out": 90.7,
                "fuel_in": 64.9,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b4",
                "id": 194,
                "flt_date": "2013-03-20 00:00:00",
                "hobbs_out": 808.1,
                "hobbs_in": 809.4,
                "fuel_out": 64.8,
                "fuel_in": 39,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b5",
                "id": 195,
                "flt_date": "2013-03-28 00:00:00",
                "hobbs_out": 809.4,
                "hobbs_in": 812.6,
                "fuel_out": 39,
                "fuel_in": 34.6,
                "fuel_purch": 55.9,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b6",
                "id": 196,
                "flt_date": "2013-04-01 00:00:00",
                "hobbs_out": 812.6,
                "hobbs_in": 816,
                "fuel_out": 34.6,
                "fuel_in": 54.2,
                "fuel_purch": 79,
                "fuel_cost": 7.02,
                "oil_added": 1,
                "oil_dipstick": 0,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4b7",
                "id": 197,
                "flt_date": "2013-04-05 00:00:00",
                "hobbs_out": 816,
                "hobbs_in": 817.1,
                "fuel_out": 54.2,
                "fuel_in": 71.8,
                "fuel_purch": 36.5,
                "fuel_cost": 6.5,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b8",
                "id": 198,
                "flt_date": "2013-04-07 00:00:00",
                "hobbs_out": 817.1,
                "hobbs_in": 818.2,
                "fuel_out": 71.8,
                "fuel_in": 49.2,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4b9",
                "id": 199,
                "flt_date": "2013-04-12 00:00:00",
                "hobbs_out": 818.2,
                "hobbs_in": 818.7,
                "fuel_out": 48.2,
                "fuel_in": 86,
                "fuel_purch": 43.7,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4ba",
                "id": 200,
                "flt_date": "2013-04-12 00:00:00",
                "hobbs_out": 818.7,
                "hobbs_in": 819.1,
                "fuel_out": 86,
                "fuel_in": 77.8,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4bb",
                "id": 201,
                "flt_date": "2013-04-13 00:00:00",
                "hobbs_out": 819.1,
                "hobbs_in": 820.1,
                "fuel_out": 77.8,
                "fuel_in": 60.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 6.5,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4bc",
                "id": 202,
                "flt_date": "2013-05-23 00:00:00",
                "hobbs_out": 823,
                "hobbs_in": 823.8,
                "fuel_out": 74,
                "fuel_in": 57.3,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": 1,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4bd",
                "id": 203,
                "flt_date": "2013-05-28 00:00:00",
                "hobbs_out": 823.8,
                "hobbs_in": 824.7,
                "fuel_out": 57.3,
                "fuel_in": 108.3,
                "fuel_purch": 68.6,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4be",
                "id": 204,
                "flt_date": "2013-06-07 00:00:00",
                "hobbs_out": 824.7,
                "hobbs_in": 825.7,
                "fuel_out": 108.3,
                "fuel_in": 89,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4bf",
                "id": 205,
                "flt_date": "2013-06-07 00:00:00",
                "hobbs_out": 825.7,
                "hobbs_in": 826.4,
                "fuel_out": 88.9,
                "fuel_in": 75.3,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c0",
                "id": 206,
                "flt_date": "2013-06-08 00:00:00",
                "hobbs_out": 826.4,
                "hobbs_in": 827.8,
                "fuel_out": 75.3,
                "fuel_in": 48.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c1",
                "id": 207,
                "flt_date": "2013-06-11 00:00:00",
                "hobbs_out": 827.8,
                "hobbs_in": 828.4,
                "fuel_out": 48.4,
                "fuel_in": 67.6,
                "fuel_purch": 30.2,
                "fuel_cost": 5.2,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c2",
                "id": 208,
                "flt_date": "2013-06-12 00:00:00",
                "hobbs_out": 828.4,
                "hobbs_in": 830,
                "fuel_out": 67.6,
                "fuel_in": 36.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c3",
                "id": 209,
                "flt_date": "2013-06-15 00:00:00",
                "hobbs_out": 830,
                "hobbs_in": 830.3,
                "fuel_out": 36.1,
                "fuel_in": 30.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c4",
                "id": 210,
                "flt_date": "2013-06-15 00:00:00",
                "hobbs_out": 830.3,
                "hobbs_in": 830.6,
                "fuel_out": 30.5,
                "fuel_in": 68.4,
                "fuel_purch": 43.2,
                "fuel_cost": 5.2,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c5",
                "id": 211,
                "flt_date": "2013-06-15 00:00:00",
                "hobbs_out": 830.6,
                "hobbs_in": 831.5,
                "fuel_out": 68.4,
                "fuel_in": 74,
                "fuel_purch": 22.7,
                "fuel_cost": 5.99,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c6",
                "id": 212,
                "flt_date": "2013-06-15 00:00:00",
                "hobbs_out": 831.5,
                "hobbs_in": 832.3,
                "fuel_out": 74,
                "fuel_in": 59,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c7",
                "id": 213,
                "flt_date": "2013-06-16 00:00:00",
                "hobbs_out": 832.3,
                "hobbs_in": 832.8,
                "fuel_out": 58,
                "fuel_in": 114,
                "fuel_purch": 65,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c8",
                "id": 214,
                "flt_date": "2013-06-16 00:00:00",
                "hobbs_out": 832.8,
                "hobbs_in": 834.2,
                "fuel_out": 114,
                "fuel_in": 88.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4c9",
                "id": 215,
                "flt_date": "2013-06-21 00:00:00",
                "hobbs_out": 834.2,
                "hobbs_in": 835.4,
                "fuel_out": 88.6,
                "fuel_in": 66,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4ca",
                "id": 216,
                "flt_date": "2013-06-22 00:00:00",
                "hobbs_out": 835.4,
                "hobbs_in": 835.8,
                "fuel_out": 65.9,
                "fuel_in": 58.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 0,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4cb",
                "id": 217,
                "flt_date": "2013-06-28 00:00:00",
                "hobbs_out": 835.8,
                "hobbs_in": 836.3,
                "fuel_out": 58.3,
                "fuel_in": 48.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4cc",
                "id": 218,
                "flt_date": "2013-06-30 00:00:00",
                "hobbs_out": 836.3,
                "hobbs_in": 837.2,
                "fuel_out": 48.2,
                "fuel_in": 103.6,
                "fuel_purch": 70.4,
                "fuel_cost": 5.3,
                "oil_added": 0,
                "oil_dipstick": 9.5,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4cd",
                "id": 219,
                "flt_date": "2013-06-30 00:00:00",
                "hobbs_out": 837.2,
                "hobbs_in": 838,
                "fuel_out": 103.6,
                "fuel_in": 88.3,
                "fuel_purch": 0,
                "fuel_cost": 6.3,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": "NULL",
                "comment": "NULL"
            },
            {
                "_id": "545163fdecf44af8e066f4ce",
                "id": 220,
                "flt_date": "2013-07-01 16:33:06",
                "hobbs_out": 838,
                "hobbs_in": 839.5,
                "fuel_out": 88.2,
                "fuel_in": 54.8,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4cf",
                "id": 221,
                "flt_date": "2013-07-20 19:35:00",
                "hobbs_out": 839.5,
                "hobbs_in": 840.5,
                "fuel_out": 54.8,
                "fuel_in": 74,
                "fuel_purch": 38.4,
                "fuel_cost": 5.35,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4d0",
                "id": 222,
                "flt_date": "2013-07-20 21:00:00",
                "hobbs_out": 840.5,
                "hobbs_in": 841.5,
                "fuel_out": 74,
                "fuel_in": 53.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": "NULL",
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4d1",
                "id": 223,
                "flt_date": "2013-07-25 20:59:03",
                "hobbs_out": 841.5,
                "hobbs_in": 841.8,
                "fuel_out": 53.5,
                "fuel_in": 47.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9.5,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4d2",
                "id": 224,
                "flt_date": "2013-07-25 21:59:03",
                "hobbs_out": 841.8,
                "hobbs_in": 842.1,
                "fuel_out": 47.4,
                "fuel_in": 108,
                "fuel_purch": 66.4,
                "fuel_cost": 5.3,
                "oil_added": 0,
                "oil_dipstick": "NULL",
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4d3",
                "id": 225,
                "flt_date": "2013-07-26 18:17:05",
                "hobbs_out": 842.1,
                "hobbs_in": 842.8,
                "fuel_out": 108,
                "fuel_in": 94.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 8.5,
                "oil_change": 0,
                "comment": "Flew MJD and around lake. 2 night landings and shot GPS18 into NEW."
            },
            {
                "_id": "545163fdecf44af8e066f4d4",
                "id": 226,
                "flt_date": "2013-08-15 00:00:00",
                "hobbs_out": 842.8,
                "hobbs_in": 843,
                "fuel_out": 94.6,
                "fuel_in": 90.2,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Very short flight around pattern to warm engine. Cloud bases ~ 700ft."
            },
            {
                "_id": "545163fdecf44af8e066f4d5",
                "id": 227,
                "flt_date": "2013-08-20 00:00:00",
                "hobbs_out": 843,
                "hobbs_in": 845.6,
                "fuel_out": 90.2,
                "fuel_in": 36,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Flew to 14M, Hollandale, MS  and back to KNEW with Bobby. Plenty of weather. Great flight to learn about weather and XM weather service."
            },
            {
                "_id": "545163fdecf44af8e066f4d6",
                "id": 228,
                "flt_date": "2013-08-30 00:00:00",
                "hobbs_out": 845.6,
                "hobbs_in": 847.2,
                "fuel_out": 36,
                "fuel_in": 48,
                "fuel_purch": 43.6,
                "fuel_cost": 5.3,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Round robin, Picayune (KMJD), Wiggins (M24), Lumberton (4R1), Tylertown (T36), Franklinton (4R7), Covington (L31), New Orleans (KNEW). RMM and I went to < 3,000 ft runways. Great time."
            },
            {
                "_id": "545163fdecf44af8e066f4d7",
                "id": 229,
                "flt_date": "2013-08-31 00:00:00",
                "hobbs_out": 847.2,
                "hobbs_in": 849.5,
                "fuel_out": 48,
                "fuel_in": 74,
                "fuel_purch": 70.1,
                "fuel_cost": 5.7,
                "oil_added": 0,
                "oil_dipstick": 8.5,
                "oil_change": 0,
                "comment": "New to MJD for fuel. MJD to Yazoo City (87i) @ 65 VFR. 87I to Stennis for the weekend. Fuel @ MJD 42.4, @ HSA 39.2."
            },
            {
                "_id": "545163fdecf44af8e066f4d8",
                "id": 230,
                "flt_date": "2013-09-01 00:00:00",
                "hobbs_out": 849.5,
                "hobbs_in": 850.4,
                "fuel_out": 74,
                "fuel_in": 56.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 8.5,
                "oil_change": 0,
                "comment": "4 T&G at NEW on 27. Shot 36 @ HSA."
            },
            {
                "_id": "545163fdecf44af8e066f4d9",
                "id": 231,
                "flt_date": "2013-09-02 00:00:00",
                "hobbs_out": 850.4,
                "hobbs_in": 852.3,
                "fuel_out": 56.5,
                "fuel_in": 76,
                "fuel_purch": 57.8,
                "fuel_cost": 6.02,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Round Robin, Stennis, Marion County (0R0), McComb(KMCB), Hammond(KHDC), Lakefront"
            },
            {
                "_id": "545163fdecf44af8e066f4da",
                "id": 232,
                "flt_date": "2013-09-06 00:00:00",
                "hobbs_out": 852.3,
                "hobbs_in": 854.1,
                "fuel_out": 76,
                "fuel_in": 39.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 1,
                "comment": "Nice flight to Bham w/Liz. Flew IFR @ 7,000. Clear, no auto-pilot. Good practice on straight & level by hand!"
            },
            {
                "_id": "545163fdecf44af8e066f4db",
                "id": 233,
                "flt_date": "2013-09-08 00:00:00",
                "hobbs_out": 854.1,
                "hobbs_in": 856,
                "fuel_out": 39.1,
                "fuel_in": 43,
                "fuel_purch": 37.4,
                "fuel_cost": 7.09,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "Landed iLS 18 @ Knew 1/2 hour IMC."
            },
            {
                "_id": "545163fdecf44af8e066f4dc",
                "id": 234,
                "flt_date": "2013-09-11 00:00:00",
                "hobbs_out": 856,
                "hobbs_in": 856.9,
                "fuel_out": 43,
                "fuel_in": 59.4,
                "fuel_purch": 35.1,
                "fuel_cost": 6.5,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "To Fairhope w/ Rick Blount. 15 minutes IMC. Beechtalk convention."
            },
            {
                "_id": "545163fdecf44af8e066f4dd",
                "id": 235,
                "flt_date": "2013-09-14 00:00:00",
                "hobbs_out": 856.9,
                "hobbs_in": 857.7,
                "fuel_out": 59.4,
                "fuel_in": 42.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Back from Faithope w/ Rick Blount. All IMC. GREAT!!"
            },
            {
                "_id": "545163fdecf44af8e066f4de",
                "id": 236,
                "flt_date": "2013-09-15 00:00:00",
                "hobbs_out": 857.7,
                "hobbs_in": 858.4,
                "fuel_out": 42.1,
                "fuel_in": 74.5,
                "fuel_purch": 46.6,
                "fuel_cost": 5.3,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "10 gallons in tip tanks."
            },
            {
                "_id": "545163fdecf44af8e066f4df",
                "id": 237,
                "flt_date": "2013-09-27 00:00:00",
                "hobbs_out": 858.4,
                "hobbs_in": 858.9,
                "fuel_out": 74.4,
                "fuel_in": 64.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "Out to East to check Leroi. AHRS failed on takeoff. Aborted first time then worked, but failed on landing."
            },
            {
                "_id": "545163fdecf44af8e066f4e0",
                "id": 238,
                "flt_date": "2013-09-29 00:00:00",
                "hobbs_out": 858.9,
                "hobbs_in": 860.5,
                "fuel_out": 64.6,
                "fuel_in": 76.4,
                "fuel_purch": 42,
                "fuel_cost": 5.3,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4e1",
                "id": 239,
                "flt_date": "2013-10-07 00:00:00",
                "hobbs_out": 860.5,
                "hobbs_in": 862.5,
                "fuel_out": 76.4,
                "fuel_in": 39.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": "To Vicksburg/Tallulah (TVR). Did GAMI test. Beautiful day."
            },
            {
                "_id": "545163fdecf44af8e066f4e2",
                "id": 240,
                "flt_date": "2013-10-09 00:00:00",
                "hobbs_out": 862.5,
                "hobbs_in": 864,
                "fuel_out": 39.5,
                "fuel_in": 62.4,
                "fuel_purch": 48.7,
                "fuel_cost": 5.3,
                "oil_added": 0,
                "oil_dipstick": 9.5,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4e3",
                "id": 241,
                "flt_date": "2013-10-12 00:00:00",
                "hobbs_out": 864,
                "hobbs_in": 865,
                "fuel_out": 62.4,
                "fuel_in": 84,
                "fuel_purch": 40.3,
                "fuel_cost": 6.1,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "To JKA W/Thomas. Shot GPS 27."
            },
            {
                "_id": "545163fdecf44af8e066f4e4",
                "id": 242,
                "flt_date": "2013-10-12 00:00:00",
                "hobbs_out": 865,
                "hobbs_in": 865.9,
                "fuel_out": 84,
                "fuel_in": 65.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4e5",
                "id": 243,
                "flt_date": "2013-10-20 00:00:00",
                "hobbs_out": 865.9,
                "hobbs_in": 866.9,
                "fuel_out": 65.4,
                "fuel_in": 48.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9.5,
                "oil_change": 0,
                "comment": "To Ocean Springs and back. Took Harper home."
            },
            {
                "_id": "545163fdecf44af8e066f4e6",
                "id": 244,
                "flt_date": "2013-10-25 00:00:00",
                "hobbs_out": 866.9,
                "hobbs_in": 867.4,
                "fuel_out": 45.6,
                "fuel_in": 36.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "To Baton Rouge to see Liz and the Bohns. Dinner at Chris'. Fun."
            },
            {
                "_id": "545163fdecf44af8e066f4e7",
                "id": 245,
                "flt_date": "2013-10-26 00:00:00",
                "hobbs_out": 867.4,
                "hobbs_in": 867.9,
                "fuel_out": 36.1,
                "fuel_in": 64.5,
                "fuel_purch": 37.9,
                "fuel_cost": 6.24,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Back from BR."
            },
            {
                "_id": "545163fdecf44af8e066f4e8",
                "id": 246,
                "flt_date": "2013-10-30 00:00:00",
                "hobbs_out": 867.9,
                "hobbs_in": 869.3,
                "fuel_out": 64.5,
                "fuel_in": 37.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "From KNEW to KECP. Nice flight."
            },
            {
                "_id": "545163fdecf44af8e066f4e9",
                "id": 247,
                "flt_date": "2013-10-31 00:00:00",
                "hobbs_out": 869.3,
                "hobbs_in": 870.1,
                "fuel_out": 37.6,
                "fuel_in": 57,
                "fuel_purch": 35,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "ECP to CQF."
            },
            {
                "_id": "545163fdecf44af8e066f4ea",
                "id": 248,
                "flt_date": "2013-10-31 00:00:00",
                "hobbs_out": 870.1,
                "hobbs_in": 871,
                "fuel_out": 57,
                "fuel_in": 40.7,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "CQF back to ECP. SHOT ILS 16 into ECP. Problem with ILS capturing localizer & glideslope."
            },
            {
                "_id": "545163fdecf44af8e066f4eb",
                "id": 249,
                "flt_date": "2013-11-04 00:00:00",
                "hobbs_out": 871,
                "hobbs_in": 871.8,
                "fuel_out": 40.7,
                "fuel_in": 27.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "ECP to CQF for annual at Continental FBO."
            },
            {
                "_id": "545163fdecf44af8e066f4ec",
                "id": 250,
                "flt_date": "2013-11-13 00:00:00",
                "hobbs_out": 872,
                "hobbs_in": 872.7,
                "fuel_out": 24.1,
                "fuel_in": 60.4,
                "fuel_purch": 48.5,
                "fuel_cost": 5.85,
                "oil_added": 0,
                "oil_dipstick": 12,
                "oil_change": 1,
                "comment": "Annual inspection at Continental Motors Fairhope. Cost 7,385.46."
            },
            {
                "_id": "545163fdecf44af8e066f4ed",
                "id": 251,
                "flt_date": "2013-11-20 00:00:00",
                "hobbs_out": 872.7,
                "hobbs_in": 873.8,
                "fuel_out": 60.4,
                "fuel_in": 37.7,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 12,
                "oil_change": 0,
                "comment": "To LCH with Monsted. CAVU."
            },
            {
                "_id": "545163fdecf44af8e066f4ee",
                "id": 252,
                "flt_date": "2013-11-22 00:00:00",
                "hobbs_out": 873.8,
                "hobbs_in": 875,
                "fuel_out": 37.7,
                "fuel_in": 51,
                "fuel_purch": 34,
                "fuel_cost": 5.94,
                "oil_added": 0,
                "oil_dipstick": 12,
                "oil_change": 0,
                "comment": "Back from LCH. IMC 20 minutes. Shot ILS18 into NEW. Great flight."
            },
            {
                "_id": "545163fdecf44af8e066f4ef",
                "id": 253,
                "flt_date": "2013-11-29 00:00:00",
                "hobbs_out": 875,
                "hobbs_in": 875.9,
                "fuel_out": 51,
                "fuel_in": 68.2,
                "fuel_purch": 34.7,
                "fuel_cost": 5.05,
                "oil_added": 0,
                "oil_dipstick": 12,
                "oil_change": 0,
                "comment": "Around shell beach, then up to MJD for fuel."
            },
            {
                "_id": "545163fdecf44af8e066f4f0",
                "id": 254,
                "flt_date": "2013-11-30 00:00:00",
                "hobbs_out": 875.9,
                "hobbs_in": 876.9,
                "fuel_out": 68.2,
                "fuel_in": 46.8,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 11.5,
                "oil_change": 0,
                "comment": "Flew Harper home and returned New Orleans with Merrick. At night. Fun!"
            },
            {
                "_id": "545163fdecf44af8e066f4f1",
                "id": 255,
                "flt_date": "2013-12-29 00:00:00",
                "hobbs_out": 876.9,
                "hobbs_in": 877.5,
                "fuel_out": 46.8,
                "fuel_in": 108.3,
                "fuel_purch": 73.1,
                "fuel_cost": 5.05,
                "oil_added": 0,
                "oil_dipstick": 12.5,
                "oil_change": 0,
                "comment": "To: MJD for fuel. Oil came up to 12.5 after sitting for a month!"
            },
            {
                "_id": "545163fdecf44af8e066f4f2",
                "id": 257,
                "flt_date": "2014-01-05 00:00:00",
                "hobbs_out": 877.5,
                "hobbs_in": 879.4,
                "fuel_out": 108.3,
                "fuel_in": 108.2,
                "fuel_purch": 37.3,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 12,
                "oil_change": 0,
                "comment": "N.O., Fairhope, Picayune, N.O."
            },
            {
                "_id": "545163fdecf44af8e066f4f3",
                "id": 258,
                "flt_date": "2014-01-07 00:00:00",
                "hobbs_out": 879.4,
                "hobbs_in": 882,
                "fuel_out": 108.2,
                "fuel_in": 63.2,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 11.2,
                "oil_change": 0,
                "comment": "Flew to Athens with Nina and Bobby. Great flight, cold as hell though."
            },
            {
                "_id": "545163fdecf44af8e066f4f4",
                "id": 259,
                "flt_date": "2014-01-07 00:00:00",
                "hobbs_out": 882,
                "hobbs_in": 884.7,
                "fuel_out": 63.2,
                "fuel_in": 60.3,
                "fuel_purch": 50.1,
                "fuel_cost": 5.99,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": "Back from Athens with Monsted. Great flying day."
            },
            {
                "_id": "545163fdecf44af8e066f4f5",
                "id": 260,
                "flt_date": "2014-01-25 00:00:00",
                "hobbs_out": 884.7,
                "hobbs_in": 886.6,
                "fuel_out": 60.3,
                "fuel_in": 74,
                "fuel_purch": 49.2,
                "fuel_cost": 5.3,
                "oil_added": 0,
                "oil_dipstick": 12,
                "oil_change": 0,
                "comment": "To Albany w/Liz to shoot quail at Nochaway Plantation. What a ball!"
            },
            {
                "_id": "545163fdecf44af8e066f4f6",
                "id": 261,
                "flt_date": "2014-01-26 00:00:00",
                "hobbs_out": 886.6,
                "hobbs_in": 888.8,
                "fuel_out": 74,
                "fuel_in": 31,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4f7",
                "id": 262,
                "flt_date": "2014-02-01 00:00:00",
                "hobbs_out": 888.8,
                "hobbs_in": 889.3,
                "fuel_out": 31.6,
                "fuel_in": 108.6,
                "fuel_purch": 85.2,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f4f8",
                "id": 263,
                "flt_date": "2014-02-09 00:00:00",
                "hobbs_out": 889.3,
                "hobbs_in": 891.5,
                "fuel_out": 108.6,
                "fuel_in": 66.4,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "Flew practice approaches with Beron. HSA, MJD, ASD, HDC, L10, NEW and hold."
            },
            {
                "_id": "545163fdecf44af8e066f4f9",
                "id": 264,
                "flt_date": "2014-02-14 00:00:00",
                "hobbs_out": 891.5,
                "hobbs_in": 893.9,
                "fuel_out": 66.4,
                "fuel_in": 66.3,
                "fuel_purch": 46.2,
                "fuel_cost": 5.75,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "To KAHN Nina parents weekend. Great flight."
            },
            {
                "_id": "545163fdecf44af8e066f4fa",
                "id": 265,
                "flt_date": "2014-02-16 00:00:00",
                "hobbs_out": 893.9,
                "hobbs_in": 897,
                "fuel_out": 66.3,
                "fuel_in": 57,
                "fuel_purch": 45.5,
                "fuel_cost": 5.99,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Flight back from Athens with Liz. Easy flight, CAVU, but big headwinds. Left Tip Tanks 1/2 full."
            },
            {
                "_id": "545163fdecf44af8e066f4fb",
                "id": 266,
                "flt_date": "2014-02-20 00:00:00",
                "hobbs_out": 897,
                "hobbs_in": 898.8,
                "fuel_out": 57,
                "fuel_in": 60,
                "fuel_purch": 32.6,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": "To Albany with Liz. Weather tricky. 20 min IMC."
            },
            {
                "_id": "545163fdecf44af8e066f4fc",
                "id": 267,
                "flt_date": "2014-02-22 00:00:00",
                "hobbs_out": 898.8,
                "hobbs_in": 901,
                "fuel_out": 60,
                "fuel_in": 48.3,
                "fuel_purch": 34,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Flight to Albany to shoot quail with the Slosses and Melanee and Jay Grenny"
            },
            {
                "_id": "545163fdecf44af8e066f4fd",
                "id": 268,
                "flt_date": "2014-03-10 00:00:00",
                "hobbs_out": 901,
                "hobbs_in": 901.6,
                "fuel_out": 48.3,
                "fuel_in": 108.3,
                "fuel_purch": 69.8,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": "MJD for fuel."
            },
            {
                "_id": "545163fdecf44af8e066f4fe",
                "id": 269,
                "flt_date": "2014-03-15 00:00:00",
                "hobbs_out": 901.6,
                "hobbs_in": 903.1,
                "fuel_out": 108.3,
                "fuel_in": 108.4,
                "fuel_purch": 30.8,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Flew in scud to 0R0, 4R1, MJD, home. Lot's weather. Pop up IFR clearance and GPS 23 approach at 0R0."
            },
            {
                "_id": "545163fdecf44af8e066f4ff",
                "id": 270,
                "flt_date": "2014-03-30 00:00:00",
                "hobbs_out": 903.1,
                "hobbs_in": 905.2,
                "fuel_out": 108.4,
                "fuel_in": 68.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "New-Btr-PTN-HUM-NEW. With Bobby. A ball and clear day."
            },
            {
                "_id": "545163fdecf44af8e066f500",
                "id": 271,
                "flt_date": "2014-04-12 00:00:00",
                "hobbs_out": 905.2,
                "hobbs_in": 906.9,
                "fuel_out": 68.5,
                "fuel_in": 78.6,
                "fuel_purch": 43.6,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "BHAM for lunch with Petie. Liz came. Good trip."
            },
            {
                "_id": "545163fdecf44af8e066f501",
                "id": 272,
                "flt_date": "2014-04-12 00:00:00",
                "hobbs_out": 906.9,
                "hobbs_in": 908.9,
                "fuel_out": 78.6,
                "fuel_in": 76.2,
                "fuel_purch": 34.3,
                "fuel_cost": 6.59,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Back from BHAM w/Liz."
            },
            {
                "_id": "545163fdecf44af8e066f502",
                "id": 273,
                "flt_date": "2014-04-13 00:00:00",
                "hobbs_out": 908.9,
                "hobbs_in": 909.7,
                "fuel_out": 76.2,
                "fuel_in": 59,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "To Acadiana Regional with Rick Blount to see Tia II, 53' Hatteras belonging to Tony Simmons. Great boat and shot GPS 16 at AYA  and got instrument time."
            },
            {
                "_id": "545163fdecf44af8e066f503",
                "id": 274,
                "flt_date": "2014-04-13 00:00:00",
                "hobbs_out": 909.7,
                "hobbs_in": 910.4,
                "fuel_out": 59,
                "fuel_in": 77.3,
                "fuel_purch": 33.4,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Back from Avery Island."
            },
            {
                "_id": "545163fdecf44af8e066f504",
                "id": 275,
                "flt_date": "2014-04-16 00:00:00",
                "hobbs_out": 910.4,
                "hobbs_in": 913.9,
                "fuel_out": 77.3,
                "fuel_in": 51.2,
                "fuel_purch": 38.1,
                "fuel_cost": 0,
                "oil_added": 1,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "To CLT to see Buzz and Patty. Great flight."
            },
            {
                "_id": "545163fdecf44af8e066f505",
                "id": 276,
                "flt_date": "2014-04-17 00:00:00",
                "hobbs_out": 913.9,
                "hobbs_in": 914.5,
                "fuel_out": 51.2,
                "fuel_in": 100.9,
                "fuel_purch": 61.3,
                "fuel_cost": 6.12,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Flew CLT - AVL. DP Hugo2, 270d to SUG direct AVL @ 8,000ft. Nice flight."
            },
            {
                "_id": "545163fdecf44af8e066f506",
                "id": 277,
                "flt_date": "2014-04-21 00:00:00",
                "hobbs_out": 914.5,
                "hobbs_in": 917.8,
                "fuel_out": 100.9,
                "fuel_in": 53,
                "fuel_purch": 12.9,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "AVL - NEW. Very nice at 8,000. Weather at NEW, flew ILS 18R. Tips are empty."
            },
            {
                "_id": "545163fdecf44af8e066f507",
                "id": 278,
                "flt_date": "2014-04-23 00:00:00",
                "hobbs_out": 917.8,
                "hobbs_in": 919,
                "fuel_out": 53,
                "fuel_in": 29.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Flew Jessica down the river."
            },
            {
                "_id": "545163fdecf44af8e066f508",
                "id": 279,
                "flt_date": "2014-04-25 00:00:00",
                "hobbs_out": 919,
                "hobbs_in": 919.9,
                "fuel_out": 29.6,
                "fuel_in": 52.8,
                "fuel_purch": 39.7,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 1,
                "comment": "To Ocean Springs and back for Harper with Merrick."
            },
            {
                "_id": "545163fdecf44af8e066f509",
                "id": 280,
                "flt_date": "2014-05-01 00:00:00",
                "hobbs_out": 919.9,
                "hobbs_in": 922.2,
                "fuel_out": 52.8,
                "fuel_in": 70.9,
                "fuel_purch": 60.4,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "To Athens to pick up Nina and Meredith Marmonde with Monsted."
            },
            {
                "_id": "545163fdecf44af8e066f50a",
                "id": 281,
                "flt_date": "2014-05-01 00:00:00",
                "hobbs_out": 922.2,
                "hobbs_in": 925.1,
                "fuel_out": 70.9,
                "fuel_in": 53.5,
                "fuel_purch": 41.6,
                "fuel_cost": 5,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "AHN to 4R3 for fuel, then on to NEW with Nina Meredith and Bobby."
            },
            {
                "_id": "545163fdecf44af8e066f50b",
                "id": 282,
                "flt_date": "2014-05-03 00:00:00",
                "hobbs_out": 925.1,
                "hobbs_in": 925.7,
                "fuel_out": 53.5,
                "fuel_in": 68,
                "fuel_purch": 25.2,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "To picayune with Monty and Julie with Liz to a party at Christovich's house. Very nice day."
            },
            {
                "_id": "545163fdecf44af8e066f50c",
                "id": 283,
                "flt_date": "2014-05-18 00:00:00",
                "hobbs_out": 925.7,
                "hobbs_in": 926.7,
                "fuel_out": 68,
                "fuel_in": 108.2,
                "fuel_purch": 60.8,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "To HSA, shot GPS 18 w/ hold, MJD, GPS 18 w/vectors to final. Thomas Beron safety pilot."
            },
            {
                "_id": "545163fdecf44af8e066f50d",
                "id": 284,
                "flt_date": "2014-06-02 00:00:00",
                "hobbs_out": 926.7,
                "hobbs_in": 929.3,
                "fuel_out": 108.2,
                "fuel_in": 56.1,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "New to Austin Executive. Very nice airport. Gas expensive."
            },
            {
                "_id": "545163fdecf44af8e066f50e",
                "id": 285,
                "flt_date": "2014-06-02 00:00:00",
                "hobbs_out": 929.3,
                "hobbs_in": 931.6,
                "fuel_out": 56.1,
                "fuel_in": 30.9,
                "fuel_purch": 17.6,
                "fuel_cost": 6.29,
                "oil_added": 0,
                "oil_dipstick": 11,
                "oil_change": 0,
                "comment": "KEDC to Marfa. Bumpy at the end of the flight. But fun."
            },
            {
                "_id": "545163fdecf44af8e066f50f",
                "id": 286,
                "flt_date": "2014-06-03 00:00:00",
                "hobbs_out": 931.6,
                "hobbs_in": 934.6,
                "fuel_out": 30.9,
                "fuel_in": 34.2,
                "fuel_purch": 51.8,
                "fuel_cost": 5.45,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Marfa to St John's Industrial Airpark. Nice flight. RMM, PM, EHS, LRS."
            },
            {
                "_id": "545163fdecf44af8e066f510",
                "id": 287,
                "flt_date": "2014-06-03 00:00:00",
                "hobbs_out": 934.6,
                "hobbs_in": 936.1,
                "fuel_out": 34.2,
                "fuel_in": 44.5,
                "fuel_purch": 40.7,
                "fuel_cost": 50.8,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "St Johns to Grand Canyon. Very high DA. Long takeoff run."
            },
            {
                "_id": "545163fdecf44af8e066f511",
                "id": 288,
                "flt_date": "2014-06-05 00:00:00",
                "hobbs_out": 936.1,
                "hobbs_in": 938.5,
                "fuel_out": 44.5,
                "fuel_in": 28.4,
                "fuel_purch": 18.1,
                "fuel_cost": 7.4,
                "oil_added": 0,
                "oil_dipstick": 9.7,
                "oil_change": 0,
                "comment": "Grand Canyon to Santa Fe. Great flight at 11,000. Plane climbed very well leaned to DA AT takeoff."
            },
            {
                "_id": "545163fdecf44af8e066f512",
                "id": 289,
                "flt_date": "2014-06-06 00:00:00",
                "hobbs_out": 938.5,
                "hobbs_in": 941.1,
                "fuel_out": 28.4,
                "fuel_in": 28.2,
                "fuel_purch": 48.8,
                "fuel_cost": 7,
                "oil_added": 1,
                "oil_dipstick": 9.7,
                "oil_change": 0,
                "comment": "Santa Fe to Kickapoo Downtown."
            },
            {
                "_id": "545163fdecf44af8e066f513",
                "id": 290,
                "flt_date": "2014-06-06 00:00:00",
                "hobbs_out": 941.1,
                "hobbs_in": 944.4,
                "fuel_out": 28.2,
                "fuel_in": 17.8,
                "fuel_purch": 44.1,
                "fuel_cost": 5.45,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Kickapoo to NOLa. Very smooth and nice flight."
            },
            {
                "_id": "545163fdecf44af8e066f514",
                "id": 291,
                "flt_date": "2014-06-21 00:00:00",
                "hobbs_out": 944.4,
                "hobbs_in": 946.3,
                "fuel_out": 17.8,
                "fuel_in": 38.4,
                "fuel_purch": 56.2,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": "To EFD with Liz and Nina. Great flight. Shot ILS 17R into Ellington Field. ILS didn't pick up signal until late in approach."
            },
            {
                "_id": "545163fdecf44af8e066f515",
                "id": 292,
                "flt_date": "2014-06-21 00:00:00",
                "hobbs_out": 946.3,
                "hobbs_in": 948,
                "fuel_out": 38.4,
                "fuel_in": 38.8,
                "fuel_purch": 36,
                "fuel_cost": 6.4,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Back to NEW from EFD @ 70. Lot's of weather to go around. Good practice."
            },
            {
                "_id": "545163fdecf44af8e066f516",
                "id": 293,
                "flt_date": "2014-06-29 00:00:00",
                "hobbs_out": 948,
                "hobbs_in": 949.1,
                "fuel_out": 38.7,
                "fuel_in": 107.4,
                "fuel_purch": 87.2,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Shot HSA ILS18, MJD GPS 18, NEW ILS 18 w/ r. Monsted safety pilot."
            },
            {
                "_id": "545163fdecf44af8e066f517",
                "id": 296,
                "flt_date": "2014-08-01 00:00:00",
                "hobbs_out": 949.1,
                "hobbs_in": 950.4,
                "fuel_out": 107.4,
                "fuel_in": 81.3,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "NEW-HSA-MJD-NEW, GPS 18@HSA, MJD, GPS 36@NEW, HOLD @HSA W/Rick Blount."
            },
            {
                "_id": "545163fdecf44af8e066f518",
                "id": 297,
                "flt_date": "2014-08-13 00:00:00",
                "hobbs_out": 950.4,
                "hobbs_in": 951,
                "fuel_out": 81.3,
                "fuel_in": 107.9,
                "fuel_purch": 37.8,
                "fuel_cost": 5.25,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "Mms for fuel."
            },
            {
                "_id": "545163fdecf44af8e066f519",
                "id": 298,
                "flt_date": "2014-08-16 00:00:00",
                "hobbs_out": 951,
                "hobbs_in": 952.8,
                "fuel_out": 107.9,
                "fuel_in": 73.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f51a",
                "id": 299,
                "flt_date": "2014-08-16 00:00:00",
                "hobbs_out": 952.8,
                "hobbs_in": 954.8,
                "fuel_out": 73.6,
                "fuel_in": 75.1,
                "fuel_purch": 40.2,
                "fuel_cost": 7.9,
                "oil_added": 1,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f51b",
                "id": 300,
                "flt_date": "2014-08-17 00:00:00",
                "hobbs_out": 954.8,
                "hobbs_in": 955.2,
                "fuel_out": 75.1,
                "fuel_in": 66.5,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 9,
                "oil_change": 0,
                "comment": "Flew around lake w/Bobby and little Bobby."
            },
            {
                "_id": "545163fdecf44af8e066f51c",
                "id": 301,
                "flt_date": "2014-09-06 00:00:00",
                "hobbs_out": 955.2,
                "hobbs_in": 956,
                "fuel_out": 66.5,
                "fuel_in": 68.7,
                "fuel_purch": 17.6,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10.5,
                "oil_change": 0,
                "comment": ""
            },
            {
                "_id": "545163fdecf44af8e066f51d",
                "id": 302,
                "flt_date": "2014-10-04 00:00:00",
                "hobbs_out": 956,
                "hobbs_in": 957.5,
                "fuel_out": 68.7,
                "fuel_in": 36.6,
                "fuel_purch": 0,
                "fuel_cost": 0,
                "oil_added": 0,
                "oil_dipstick": 10,
                "oil_change": 0,
                "comment": "to Angola w/RMM."
            }];

        $scope.tableParams = new ngTableParams({
            page: 1,            // show first page
            count: 100           // count per page
        }, {
            total: data.length, // length of data
            getData: function($defer, params) {
                $defer.resolve(data.slice((params.page() - 1) * params.count(), params.page() * params.count()));
            }
        });
    });